#!/bin/sh

psql -U postgres <<EOS
    SELECT 'CREATE DATABASE ${DB_PGSQL_DBNAME}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_PGSQL_DBNAME}')\gexec
    SELECT 'CREATE USER ${DB_PGSQL_USER}  WITH SUPERUSER PASSWORD ''${DB_PGSQL_PASSWORD}'' ' WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = '${DB_PGSQL_USER}')\gexec

EOS

#SELECT 'CREATE DATABASE ${DB_PGSQL_DBNAME}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_PGSQL_DBNAME}')\gexec
#CREATE USER ${DB_PGSQL_USER} WITH SUPERUSER PASSWORD '${DB_PGSQL_PASSWORD}';

